services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - app-network

  app:
    build: .
    command: foreman start
    volumes:
      - .:/opt/app
      - gems_volume:/usr/local/bundle
      - node_modules_volume:/opt/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  gems_volume:
  node_modules_volume:

networks:
  app-network:
