version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: foreman start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

networks:
  default:
    name: collab-coffer-network
