name: CollabCoffer Docker-Compose CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Compose services
        run: |
          docker-compose build --build-arg BUILDKIT_INLINE_CACHE=1
          docker-compose push
      - name: Prepare the Rails test database
        run: docker-compose run --rm app bundle exec rails db:test:prepare
      # TODO: Uncomment the following lines once the test suite is ready
      # - name: Run the Rails test suite
      #   run: docker-compose run --rm app bundle exec rspec
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Compose services
        run: |
          docker-compose build --build-arg BUILDKIT_INLINE_CACHE=1
          docker-compose push
      - name: Run Brakeman
        run: docker-compose run --rm app bundle exec brakeman -q -w2
      - name: Run Rubocop
        run: docker-compose run --rm app bundle exec rubocop --parallel
